// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElInput: typeof import('element-plus/es')['ElInput']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    Icon: typeof import('./../components/icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export { }
